language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install coverage
  - pip install green codecov
  - pip install .

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - beams --help
  - green -vvv --run-coverage

after_script:
  - python -m codecov
