package:
    name: beams
    version: 0.1.0

source:
    git_rev: dev
    git_url: https://github.com/computational-metabolomics/beams.git

build:
    number: 0
    noarch: python
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - future
        - networkx
        - numpy
        - scipy
        - pandas
        - requests
        - biopython
        - pyteomics
        - matplotlib
        - tqdm
        - seaborn
        - pyqt
    run:
        - python
        - setuptools
        - future
        - networkx
        - numpy
        - scipy
        - pandas
        - requests
        - biopython
        - pyteomics
        - matplotlib
        - tqdm
        - seaborn
        - pyqt

test:
    commands:
        - beams --help
    imports:
        - beams

about:
    home: https://github.com/computational-metabolomics/beams
    license: GPLv3

extra:
    copy_test_source_files: true
    final: true